version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: kuilinga_db
      POSTGRES_USER: kuilinga_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_log:
