version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: kuilinga_db
      POSTGRES_USER: kuilinga_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  hivemq:
    image: hivemq/hivemq-ce:latest
    ports:
      - "1883:1883"
      - "8888:8080" # HiveMQ Control Center
    volumes:
      - hivemq_data:/opt/hivemq/data
      - hivemq_extensions:/opt/hivemq/extensions
      - hivemq_log:/opt/hivemq/log

volumes:
  postgres_data:
  hivemq_data:
  hivemq_extensions:
  hivemq_log:
